# Labeler configuration
# Applied by .github/workflows/labeler.yml

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - "*.md"
          - "docs/**"
          - "content/**"

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - "go.mod"
          - "go.sum"

go:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.go"

github_actions:
  - changed-files:
      - any-glob-to-any-file:
          - ".github/workflows/**"
          - ".github/*.yml"

docker:
  - changed-files:
      - any-glob-to-any-file:
          - "Dockerfile*"
