project_name: kvs

env:
- GO111MODULE=on
- GOPROXY=https://goproxy.io

before:
  hooks:
  - go mod download

builds:
  - id: kvs
    binary: kvs
    main: cmd/kvs/main.go
    env:
    - CGO_ENABLED=0
    goos:
    - darwin
    - linux
    goarch:
    - amd64

archives:
- format: tar.gz
  format_overrides:
  - goos: windows
    format: zip
  files:
    - LICENSE
    - README.md
    - CHANGELOG.md
    - CODE_OF_CONDUCT.md
    - CONTRIBUTING.md

changelog:
  skip: true

checksum:
  algorithm: sha256
  name_template: 'CHECKSUMS'

# TODO: brews:

dockers:
- binaries:
  - kvs
  builds:
  - kvs
  dockerfile: Dockerfile.goreleaser
  image_templates:
  - "ghcr.io/skyoo2003/kvs:{{ .Tag }}-alpine"
  - "ghcr.io/skyoo2003/kvs:v{{ .Major }}.{{ .Minor }}-alpine"
  - "ghcr.io/skyoo2003/kvs:v{{ .Major }}-alpine"
  - "ghcr.io/skyoo2003/kvs:latest-alpine"

release:
  github:
    owner: skyoo2003
    name: kvs
  name_template: "v{{ .Version }}"
