version: 2

project_name: kvs

env:
- GO111MODULE=on
- CGO_ENABLED=0

before:
  hooks:
  - go mod download

builds:
- id: kvs
  binary: kvs
  dir: cmd/kvs
  main: .
  ldflags:
  - -s -w -X main.version={{ .Version }}
  goos:
  - darwin
  - linux
  - windows
  goarch:
  - 386
  - amd64
  - arm
  - arm64
  goarm:
  - 6
  - 7
  ignore:
  - goos: darwin
    goarch: 386
  - goos: linux
    goarch: arm
    goarm: 6

archives:
- id: kvs
  formats: [ tar.gz ]
  format_overrides:
  - goos: windows
    formats: [ zip ]
  files:
    - LICENSE
    - README.md
    - CHANGELOG.md
    - CODE_OF_CONDUCT.md

changelog:
  disable: false

checksum:
  algorithm: sha256
  name_template: 'CHECKSUMS'

dockers_v2:
- images:
  - ghcr.io/skyoo2003/kvs
  dockerfile: Dockerfile.goreleaser
  ids:
  - kvs
  platforms:
  - linux/amd64
  - linux/arm64
  sbom: false
  flags:
  - "--provenance=false"
  tags:
  - "{{ .Tag }}-alpine"
  - "v{{ .Major }}.{{ .Minor }}-alpine"
  - "v{{ .Major }}-alpine"
  - "latest-alpine"
  labels:
    org.opencontainers.image.created: "{{ .Date }}"
    org.opencontainers.image.source: "https://github.com/skyoo2003/kvs"
    org.opencontainers.image.title: "{{ .ProjectName }}"
    org.opencontainers.image.revision: "{{ .FullCommit }}"
    org.opencontainers.image.version: "{{ .Version }}"

release:
  github:
    owner: skyoo2003
    name: kvs
  name_template: "v{{ .Version }}"
  disable: false
  mode: replace
