version: 2

project_name: kvs

env:
- GO111MODULE=on
- CGO_ENABLED=0

before:
  hooks:
  - go mod download

builds:
- id: kvs
  binary: kvs
  main: cmd/kvs/main.go
  ldflags:
  - -s -w -X main.version={{ .Version }}
  goos:
  - darwin
  - linux
  - windows
  goarch:
  - 386
  - amd64
  - arm
  - arm64
  goarm:
  - 6
  - 7
  ignore:
  - goos: darwin
    goarch: 386
  - goos: linux
    goarch: arm
    goarm: 6

archives:
- id: kvs
  format: tar.gz
  format_overrides:
  - goos: windows
    format: zip
  files:
    - LICENSE
    - README.md
    - CHANGELOG.md
    - CODE_OF_CONDUCT.md

changelog:
  disable: false

checksum:
  algorithm: sha256
  name_template: 'CHECKSUMS'

brews:
- ids:
  - kvs
  name: kvs
  tap:
    owner: skyoo2003
    name: homebrew-tap
    token: "{{ .Env.GITHUB_TOKEN }}"
  folder: Formula
  url_template: "https://github.com/skyoo2003/kvs/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
  commit_author:
    name: Sung-Kyu Yoo
    email: skyoo2003@gmail.com
  homepage: "https://github.com/skyoo2003/kvs"
  description: "A simple key-value store"
  license: "MIT"
  test: |
    system "#{bin}/kvs -v"
  install: |
    bin.install "kvs"
  skip_upload: false

dockers_v2:
- images:
  - ghcr.io/skyoo2003/kvs
  dockerfile: Dockerfile.goreleaser
  ids:
  - kvs
  sbom: false
  flags:
  - "--provenance=false"
  tags:
  - "{{ .Tag }}-alpine"
  - "v{{ .Major }}.{{ .Minor }}-alpine"
  - "v{{ .Major }}-alpine"
  - "latest-alpine"
  labels:
    org.opencontainers.image.created: "{{ .Date }}"
    org.opencontainers.image.source: "https://github.com/skyoo2003/kvs"
    org.opencontainers.image.title: "{{ .ProjectName }}"
    org.opencontainers.image.revision: "{{ .FullCommit }}"
    org.opencontainers.image.version: "{{ .Version }}"

release:
  github:
    owner: skyoo2003
    name: kvs
  name_template: "v{{ .Version }}"
  disable: false
  mode: replace
