FROM --platform=$BUILDPLATFORM alpine:3.24

RUN adduser --system --home /kvs appuser
VOLUME /kvs
WORKDIR /kvs
ARG TARGETOS
ARG TARGETARCH
COPY ${TARGETOS}/${TARGETARCH}/kvs /usr/bin/kvs

EXPOSE 3456

USER appuser
ENTRYPOINT ["kvs"]
