name: CI

on:
  push:
    branches:
    - main
    paths:
    - "**/*.go"
    - "go.mod"
    - "go.sum"
    - "README.md"
    - ".goreleaser.yml"
    - "Makefile"
    - ".github/workflows/*.y*ml"
    - "**/*.tmpl"
  pull_request:
    branches:
    - main
    paths:
    - "**/*.go"
    - "go.mod"
    - "go.sum"
    - "README.md"
    - ".goreleaser.yml"
    - "Makefile"
    - ".github/workflows/*.y*ml"
    - "**/*.tmpl"

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        go-version: [ '1.24' ]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout the code
      uses: actions/checkout@v7.0.0
    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
    - name: Execute golangci-lint
      uses: golangci/golangci-lint-action@v6.1.1
      with:
        version: v1.64.8
    - name: Go test
      run: make test
    - name: Go build
      run: make build
