name: Release

on:
  push:
    tags:
    - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2
    - name: Set up Go 1.15
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
    - name: Get current tag name
      id: getTag
      uses: olegtarasov/get-tag@v2
    - name: Get current changelog
      id: getChangelog
      run: echo ::set-output name=changelog::$(cat changes/${{ steps.getTag.outputs.tag }}.md)
    - name: Login to Docker Registry
      run: >
        echo "${{ secrets.GH_PAT }}" |
        docker login docker.pkg.github.com -u skyoo2003 --password-stdin
    - name: Execute GoReleaser
      uses: goreleaser/goreleaser-action@v2
      with:
        version: latest
        args: release --rm-dist --release-notes=${{ steps.getChangelog.outputs.changelog }}
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}
    - name: Upload assets
      uses: actions/upload-artifact@v2
      with:
        name: kvs
        path: dist/*
